source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'Example' do
  use_frameworks!
  inhibit_all_warnings!

  #pod 'AzCore'
  pod 'AzCall'

  target 'ExampleTests' do
    inherit! :search_paths
  end

  target 'ExampleUITests' do
    inherit! :search_paths
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
